name: archimate-application
filter:
  hierarchy_level:
    index: 0
    values: [application, common]
includes:
  - _archimate-stereotypes.puml
  - _archimate-glyphs.puml
grouping:
  by_field: hierarchy_0
  stereotype_pattern: "{hierarchy_0|capitalize}Grouping"
layout:
  nesting_connection_classes: [nesting]
  flow_connection_classes: [flow]
