---
artifact-id: ARC@1777473085.eVg5bD.architecture-modelling-planning
artifact-type: diagram
name: Architecture Modelling & Planning
version: 0.1.0
status: draft
diagram-type: archimate-layered
entity-ids-used:
- FNC@1777409722.ErTqVT.scope-formulate-modelling-task
- FNC@1777472861.HgWMdN.decide-changes-to-plan-or-implement
- FNC@1777390445.NGjUCa.verify-artifact-integrity-coherence
- FNC@1777390444.lLdx12.discover-relevant-architecture-content
- FNC@1777409722.rkx32U.determine-required-changes-to-architecture-content
- FNC@1777409722.saMRQ0.author-architecture-documents
- FNC@1777390449.uzJGYp.author-diagrams
- FNC@1777390448.yuFXVJ.author-model-artifacts
- JNO@1777467627.chqH1_.inclusive-or-for-architecture-work
- PRC@1776635640.U4aAdh.architecture-modelling-planning
connection-ids-used:
- FNC@1777472861.HgWMdN---FNC@1777409722.rkx32U@@archimate-triggering
- FNC@1777390444.lLdx12---FNC@1777472861.HgWMdN@@archimate-triggering
- FNC@1777409722.ErTqVT---FNC@1777390444.lLdx12@@archimate-triggering
- FNC@1777390448.yuFXVJ---FNC@1777390445.NGjUCa@@archimate-triggering
- FNC@1777390449.uzJGYp---FNC@1777390445.NGjUCa@@archimate-triggering
- FNC@1777409722.saMRQ0---FNC@1777390445.NGjUCa@@archimate-triggering
- FNC@1777409722.rkx32U---JNO@1777467627.chqH1_@@archimate-triggering
- JNO@1777467627.chqH1_---FNC@1777390448.yuFXVJ@@archimate-triggering
- JNO@1777467627.chqH1_---FNC@1777390449.uzJGYp@@archimate-triggering
- JNO@1777467627.chqH1_---FNC@1777409722.saMRQ0@@archimate-triggering
- PRC@1776635640.U4aAdh---FNC@1777409722.saMRQ0@@archimate-aggregation
- PRC@1776635640.U4aAdh---FNC@1777390449.uzJGYp@@archimate-aggregation
- PRC@1776635640.U4aAdh---FNC@1777390448.yuFXVJ@@archimate-aggregation
- PRC@1776635640.U4aAdh---FNC@1777409722.rkx32U@@archimate-aggregation
- PRC@1776635640.U4aAdh---FNC@1777390444.lLdx12@@archimate-aggregation
- PRC@1776635640.U4aAdh---FNC@1777390445.NGjUCa@@archimate-aggregation
last-updated: '2026-07-19'
---
@startuml architecture-modelling---planning
hide stereotype

skinparam defaultFontName "Helvetica Neue, Helvetica, Arial, sans-serif"
skinparam defaultFontSize 12
skinparam shadowing false
skinparam roundcorner 4
skinparam backgroundColor #FAFAFA

skinparam linetype ortho
skinparam nodesep 60
skinparam ranksep 80
!define Rel_Triggering(from, to, label) from --> to
!define Rel_Realization(from, to, label) from ..|> to
!define Rel_Realization_Up(from, to, label) from ..|> to
!define Rel_Serving(from, to, label) from --> to
!define Rel_Association(from, to, label) from -- to
!define Rel_Association_Left(from, to, label) from -- to
!define Rel_Association_Right(from, to, label) from -- to
!define Rel_Access(from, to, label) from ..> to
!define Rel_Influence(from, to, label) from ..> to
skinparam rectangle<<CommonGrouping>> {
  BackgroundColor #EDE8E1
  BorderColor #8C7E6A
}
skinparam rectangle<<function>> {
  BackgroundColor #E0D8CC
  BorderColor #8C7E6A
}
skinparam rectangle<<process>> {
  BackgroundColor #E0D8CC
  BorderColor #8C7E6A
}
sprite $archimate_function <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M2.9 11.7V5.4L8 3.1l5.1 2.3v6.3L8 9.2z"  fill="#252327" stroke="none"/></svg>
sprite $archimate_process <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M2.6 4.1h6.3V2.8l4.5 5.2-4.5 5.2v-1.3H2.6z"  fill="#252327" stroke="none"/></svg>

top to bottom direction

title Architecture Modelling & Planning

rectangle "Processes" <<CommonGrouping>> {
  rectangle "<$archimate_process{scale=1.5}> Architecture Modelling & Planning «Business Process»" <<process>> as PRC_U4aAdh {
    rectangle "<$archimate_function{scale=1.5}> Verify Artifact Integrity & Coherence «Application Function»" <<function>> as FNC_NGjUCa
    rectangle "<$archimate_function{scale=1.5}> Discover Relevant Architecture Content «Application Function»" <<function>> as FNC_lLdx12
    rectangle "<$archimate_function{scale=1.5}> Determine Required Changes to Architecture Content «Business Function»" <<function>> as FNC_rkx32U
    rectangle "<$archimate_function{scale=1.5}> Author Architecture Documents «Business Function»" <<function>> as FNC_saMRQ0
    rectangle "<$archimate_function{scale=1.5}> Author Diagrams «Business Function»" <<function>> as FNC_uzJGYp
    rectangle "<$archimate_function{scale=1.5}> Author Model Artifacts «Business Function»" <<function>> as FNC_yuFXVJ
    circle " " as JNO_chqH1_
    FNC_lLdx12 -[hidden]down- FNC_rkx32U
    FNC_rkx32U -[hidden]down- JNO_chqH1_
    JNO_chqH1_ -[hidden]down- FNC_saMRQ0
    FNC_saMRQ0 -[hidden]right- FNC_uzJGYp
    FNC_uzJGYp -[hidden]right- FNC_yuFXVJ
    FNC_yuFXVJ -[hidden]down- FNC_NGjUCa
    JNO_chqH1_ -[hidden]down- FNC_saMRQ0
    JNO_chqH1_ -[hidden]down- FNC_uzJGYp
    JNO_chqH1_ -[hidden]down- FNC_yuFXVJ
  }
}

rectangle "Functions" <<CommonGrouping>> {
  rectangle "<$archimate_function{scale=1.5}> Scope & Formulate Modelling Task «Business Function»" <<function>> as FNC_ErTqVT
  rectangle "<$archimate_function{scale=1.5}> Decide Changes to Plan or Implement «Business Function»" <<function>> as FNC_HgWMdN
}
FNC_ErTqVT -[hidden]down- FNC_HgWMdN
PRC_U4aAdh -[hidden]down- FNC_ErTqVT

' Connections
FNC_HgWMdN --> FNC_rkx32U
FNC_lLdx12 --> FNC_HgWMdN
FNC_ErTqVT --> FNC_lLdx12
FNC_yuFXVJ --> FNC_NGjUCa
FNC_uzJGYp --> FNC_NGjUCa
FNC_saMRQ0 --> FNC_NGjUCa
FNC_rkx32U --> JNO_chqH1_
JNO_chqH1_ --> FNC_yuFXVJ
JNO_chqH1_ --> FNC_uzJGYp
JNO_chqH1_ --> FNC_saMRQ0

@enduml
