#!/usr/bin/env python3
"""Generate TypeScript type literal unions from the Python module registry.

Run from the project root:
    uv run tools/generate_types.py
"""

from __future__ import annotations

from pathlib import Path

from src.infrastructure.app_bootstrap import build_module_registry

_OUTPUT = Path(__file__).parent / "gui" / "src" / "domain" / "types.generated.ts"

_HEADER = (
    "// This file is auto-generated by tools/generate_types.py — do not edit manually.\n"
    "// Regenerate with: uv run tools/generate_types.py (from project root)\n\n"
)


def _const_array(const_name: str, type_name: str, values: list[str]) -> str:
    items = ",\n  ".join(f'"{v}"' for v in values)
    return (
        f"export const {const_name} = [\n  {items},\n] as const\n"
        f"export type {type_name} = typeof {const_name}[number]\n\n"
    )


def main() -> None:
    registry = build_module_registry()

    entity_types = sorted(registry.all_entity_types().keys())
    connection_types = sorted(registry.all_connection_types().keys())
    domain_names = registry.domain_order() + ["unknown"]
    diagram_types = sorted(registry.all_diagram_types().keys())

    out = _HEADER
    out += _const_array("ENTITY_TYPE_NAMES", "EntityTypeName", entity_types)
    out += _const_array("CONNECTION_TYPE_NAMES", "ConnectionTypeName", connection_types)
    out += _const_array("DOMAIN_NAMES", "DomainName", domain_names)
    out += _const_array("DIAGRAM_TYPE_NAMES", "DiagramTypeName", diagram_types)

    _OUTPUT.write_text(out, encoding="utf-8")
    print(f"Generated {_OUTPUT}")


if __name__ == "__main__":
    main()
