"""Characterization snapshot for pre-ConceptScope diagram-type filters."""

from __future__ import annotations

from src.infrastructure.app_bootstrap import build_module_registry

ARCHIMATE_CONNECTION_TYPES = (
    "activity-data-association",
    "activity-decision",
    "activity-message-flow",
    "activity-sequence-flow",
    "archimate-access",
    "archimate-aggregation",
    "archimate-assignment",
    "archimate-association",
    "archimate-composition",
    "archimate-flow",
    "archimate-influence",
    "archimate-realization",
    "archimate-serving",
    "archimate-specialization",
    "archimate-triggering",
    "er-many-to-many",
    "er-one-to-many",
    "er-one-to-one",
    "sequence-asynchronous",
    "sequence-create",
    "sequence-destroy",
    "sequence-return",
    "sequence-synchronous",
    "usecase-association",
    "usecase-extend",
    "usecase-generalization",
    "usecase-include",
)

ALL_CONNECTION_TYPES = (
    "accountable-for",
    "activity-data-association",
    "activity-decision",
    "activity-message-flow",
    "activity-sequence-flow",
    "acts-on",
    "allocation",
    "archimate-access",
    "archimate-aggregation",
    "archimate-assignment",
    "archimate-association",
    "archimate-composition",
    "archimate-flow",
    "archimate-influence",
    "archimate-realization",
    "archimate-serving",
    "archimate-specialization",
    "archimate-triggering",
    "assesses",
    "by-controller",
    "c4-uses",
    "complies-with",
    "concerns",
    "derives",
    "dt-aggregation",
    "dt-association",
    "dt-composition",
    "dt-dependency",
    "dt-generalization",
    "er-many-to-many",
    "er-one-to-many",
    "er-one-to-one",
    "evidenced-by",
    "explains",
    "feature-membership",
    "feature-typing",
    "feedback",
    "flow-connection",
    "investigates",
    "issues",
    "leads-to",
    "refines",
    "responsible-for",
    "satisfy",
    "seq-from",
    "seq-to",
    "sequence-asynchronous",
    "sequence-create",
    "sequence-destroy",
    "sequence-return",
    "sequence-synchronous",
    "specialization",
    "step-contains",
    "step-else",
    "step-flow",
    "step-fork-branch",
    "step-in-lane",
    "step-note-of",
    "step-then",
    "swimlane-maps-to",
    "treated-by",
    "usecase-association",
    "usecase-extend",
    "usecase-generalization",
    "usecase-include",
)

C4_ACCEPTS_CONNECTION_TYPES = (
    "activity-data-association",
    "activity-decision",
    "activity-message-flow",
    "activity-sequence-flow",
    "archimate-access",
    "archimate-aggregation",
    "archimate-assignment",
    "archimate-association",
    "archimate-composition",
    "archimate-flow",
    "archimate-influence",
    "archimate-realization",
    "archimate-serving",
    "archimate-specialization",
    "archimate-triggering",
    "c4-uses",
    "dt-aggregation",
    "dt-association",
    "dt-composition",
    "dt-dependency",
    "dt-generalization",
    "er-many-to-many",
    "er-one-to-many",
    "er-one-to-one",
    "seq-from",
    "seq-to",
    "sequence-asynchronous",
    "sequence-create",
    "sequence-destroy",
    "sequence-return",
    "sequence-synchronous",
    "step-contains",
    "step-else",
    "step-flow",
    "step-fork-branch",
    "step-in-lane",
    "step-note-of",
    "step-then",
    "swimlane-maps-to",
    "usecase-association",
    "usecase-extend",
    "usecase-generalization",
    "usecase-include",
)

EXPECTED_ENTITY_TYPES = {
    "activity": (),
    "archimate-application": (
        "and-junction",
        "application-component",
        "application-interface",
        "collaboration",
        "data-object",
        "event",
        "function",
        "global-artifact-reference",
        "grouping",
        "location",
        "or-junction",
        "path",
        "process",
        "role",
        "service",
    ),
    "archimate-business": (
        "and-junction",
        "business-actor",
        "business-interface",
        "business-object",
        "collaboration",
        "event",
        "function",
        "global-artifact-reference",
        "grouping",
        "location",
        "or-junction",
        "path",
        "process",
        "product",
        "role",
        "service",
    ),
    "archimate-implementation": (
        "deliverable",
        "plateau",
        "work-package",
    ),
    "archimate-layered": (
        "and-junction",
        "application-component",
        "application-interface",
        "artifact",
        "assessment",
        "business-actor",
        "business-interface",
        "business-object",
        "capability",
        "collaboration",
        "communication-network",
        "course-of-action",
        "data-object",
        "deliverable",
        "device",
        "distribution-network",
        "driver",
        "equipment",
        "event",
        "facility",
        "function",
        "global-artifact-reference",
        "goal",
        "grouping",
        "location",
        "material",
        "meaning",
        "or-junction",
        "outcome",
        "path",
        "plateau",
        "principle",
        "process",
        "product",
        "requirement",
        "resource",
        "role",
        "service",
        "stakeholder",
        "system-software",
        "technology-interface",
        "technology-node",
        "value",
        "value-stream",
        "work-package",
    ),
    "archimate-motivation": (
        "assessment",
        "driver",
        "goal",
        "meaning",
        "outcome",
        "principle",
        "requirement",
        "stakeholder",
        "value",
    ),
    "archimate-strategy": (
        "and-junction",
        "capability",
        "collaboration",
        "course-of-action",
        "event",
        "function",
        "global-artifact-reference",
        "grouping",
        "location",
        "or-junction",
        "path",
        "process",
        "resource",
        "role",
        "service",
        "value-stream",
    ),
    "archimate-technology": (
        "and-junction",
        "artifact",
        "collaboration",
        "communication-network",
        "device",
        "distribution-network",
        "equipment",
        "event",
        "facility",
        "function",
        "global-artifact-reference",
        "grouping",
        "location",
        "material",
        "or-junction",
        "path",
        "process",
        "role",
        "service",
        "system-software",
        "technology-interface",
        "technology-node",
    ),
    "bowtie": (),
    "c4-component": (
        "application-component",
        "business-actor",
        "data-object",
        "function",
        "role",
        "service",
    ),
    "c4-container": (
        "application-component",
        "business-actor",
        "data-object",
        "role",
        "service",
    ),
    "c4-system-context": (
        "application-component",
        "business-actor",
        "role",
        "service",
    ),
    "control-structure": (),
    "datatype": (),
    "gsn": (),
    "matrix": (
        "action-definition",
        "action-usage",
        "and-junction",
        "application-component",
        "application-interface",
        "artifact",
        "assessment",
        "assurance-constraint",
        "business-actor",
        "business-interface",
        "business-object",
        "capability",
        "collaboration",
        "communication-network",
        "control-action",
        "control-structure-node",
        "corrective-action",
        "course-of-action",
        "data-object",
        "deliverable",
        "device",
        "distribution-network",
        "driver",
        "equipment",
        "event",
        "evidence",
        "facility",
        "function",
        "global-artifact-reference",
        "goal",
        "grouping",
        "hazard",
        "incident",
        "item-definition",
        "item-usage",
        "location",
        "loss",
        "loss-scenario",
        "material",
        "meaning",
        "obligation",
        "or-junction",
        "outcome",
        "part-definition",
        "part-usage",
        "path",
        "plateau",
        "port-definition",
        "port-usage",
        "principle",
        "process",
        "product",
        "requirement",
        "requirement-definition",
        "requirement-usage",
        "resource",
        "risk",
        "role",
        "service",
        "stakeholder",
        "system-software",
        "technology-interface",
        "technology-node",
        "unsafe-control-action",
        "value",
        "value-stream",
        "work-package",
    ),
    "sequence": (),
    "uca-matrix": (),
}

EXPECTED_CONNECTION_TYPES = {
    "activity": (
        "step-contains",
        "step-else",
        "step-flow",
        "step-fork-branch",
        "step-in-lane",
        "step-note-of",
        "step-then",
        "swimlane-maps-to",
    ),
    "archimate-application": ARCHIMATE_CONNECTION_TYPES,
    "archimate-business": ARCHIMATE_CONNECTION_TYPES,
    "archimate-implementation": ARCHIMATE_CONNECTION_TYPES,
    "archimate-layered": ARCHIMATE_CONNECTION_TYPES,
    "archimate-motivation": ARCHIMATE_CONNECTION_TYPES,
    "archimate-strategy": ARCHIMATE_CONNECTION_TYPES,
    "archimate-technology": ARCHIMATE_CONNECTION_TYPES,
    "bowtie": (),
    "c4-component": ALL_CONNECTION_TYPES,
    "c4-container": ALL_CONNECTION_TYPES,
    "c4-system-context": ALL_CONNECTION_TYPES,
    "control-structure": (),
    "datatype": ("dt-aggregation", "dt-association", "dt-composition", "dt-dependency", "dt-generalization"),
    "gsn": (),
    "matrix": ALL_CONNECTION_TYPES,
    "sequence": ("seq-from", "seq-to"),
    "uca-matrix": (),
}


def test_registered_diagram_type_effective_entity_types_snapshot() -> None:
    registry = build_module_registry(complete_vocabulary=True)

    actual = {
        str(name): tuple(sorted(str(entity_type) for entity_type in module.effective_entity_types(registry)))
        for name, module in registry.all_diagram_types().items()
    }

    assert actual == EXPECTED_ENTITY_TYPES


def test_registered_diagram_type_accepts_connection_type_snapshot(monkeypatch) -> None:
    from src.infrastructure import app_bootstrap

    registry = build_module_registry(complete_vocabulary=True)
    monkeypatch.setattr(app_bootstrap, "get_module_registry", lambda: registry)
    all_connection_types = tuple(registry.all_connection_types())

    actual = {
        str(name): tuple(
            sorted(
                str(connection_type)
                for connection_type in all_connection_types
                if module.accepts_connection_type(connection_type)
            )
        )
        for name, module in registry.all_diagram_types().items()
    }

    assert actual == EXPECTED_CONNECTION_TYPES
