"""
generate_macros.py — Regenerate _macros.puml from entity §display ###archimate blocks.

Usage:
    uv run python -m src.tools.generate_macros [REPO_ROOT]

The script scans every .md entity file under <REPO_ROOT>/model/ for a
§display ###archimate block, extracts domain/element-type/label/alias fields,
and writes <REPO_ROOT>/diagram-catalog/_macros.puml.

Alias convention (PlantUML):
    Aliases follow the pattern TYPE_random (e.g. DRV_Qw7Er1).
    In diagram source files, reference elements by their alias.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_DISPLAY_SECTION = re.compile(r"<!--\s*§display\s*-->", re.IGNORECASE)
_ARCHIMATE_H3 = re.compile(r"###\s*archimate\b", re.IGNORECASE)
_YAML_FENCE = re.compile(r"```ya?ml\s*\n(.*?)```", re.DOTALL)


def _extract_archimate_block(content: str) -> dict | None:
    """Return the parsed archimate YAML block from §display, or None."""
    m = _DISPLAY_SECTION.search(content)
    if not m:
        return None
    display_text = content[m.end():]
    h3 = _ARCHIMATE_H3.search(display_text)
    if not h3:
        return None
    after_h3 = display_text[h3.end():]
    fence = _YAML_FENCE.search(after_h3)
    if not fence:
        return None
    try:
        return yaml.safe_load(fence.group(1)) or {}
    except yaml.YAMLError:
        return None


_DOMAIN_ORDER = {
    "motivation": 0,
    "strategy": 1,
    "common": 2,
    "business": 3,
    "application": 4,
    "technology": 5,
    "physical": 6,
    "implementation": 7,
}

_PREFIX_ORDER = [
    "STK", "DRV", "ASM", "GOL", "OUT", "PRI", "REQ", "CST", "MEA", "VAL",
    "CAP", "VS", "RES", "COA",
    "SRV", "PRC", "FNC", "INT", "EVT", "ROL",
    "ACT", "BCO", "BIF", "BPR", "BFN", "BIA", "BEV", "BSV", "BOB",
    "APP", "ACO", "AIF", "AFN", "AIA", "APR", "AEV", "ASV", "DOB",
    "NOD", "DEV", "SSW", "TCO", "TIF", "PTH", "NET", "TFN", "TPR",
    "TIA", "TEV", "TSV", "ART",
    "EQP", "FAC", "DIS", "MAT",
    "WP", "DEL", "IEV", "GAP", "PLT",
]


def _sort_key(entry: tuple[str, str, str]) -> tuple[int, int, str]:
    """Sort by domain → prefix → alias."""
    domain, _, alias = entry
    prefix = alias.split("_")[0] if "_" in alias else alias
    domain_idx = _DOMAIN_ORDER.get(domain.lower(), 99)
    prefix_idx = _PREFIX_ORDER.index(prefix) if prefix in _PREFIX_ORDER else 99
    return domain_idx, prefix_idx, alias


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_macros(repo_root: Path) -> Path:
    """Scan repo_root/model/ and write diagram-catalog/_macros.puml.

    Returns the path to the written file.
    """
    entities_root = repo_root / "model"
    if not entities_root.is_dir():
        raise FileNotFoundError(f"model/ not found under {repo_root}")

    entries: list[tuple[str, str, str]] = []  # (domain, macro_line, alias)

    for md_file in sorted(entities_root.rglob("*.md")):
        if md_file.name.endswith(".outgoing.md"):
            continue
        content = md_file.read_text(encoding="utf-8")
        archimate = _extract_archimate_block(content)
        if not archimate:
            continue

        label = archimate.get("label", "")
        element_type = archimate.get("element-type", "")
        alias_raw = archimate.get("alias", "")

        if not (label and element_type and alias_raw):
            continue

        alias = alias_raw.replace("-", "_")
        macro_name = f"DECL_{alias}"

        # Derive domain from directory path or from display block
        domain = archimate.get("domain", "")
        if not domain:
            rel = md_file.relative_to(entities_root)
            domain = rel.parts[0] if rel.parts else "unknown"

        macro_line = f'!define {macro_name} rectangle "{label}" <<{element_type}>> as {alias}'
        entries.append((domain, macro_line, alias))

    entries.sort(key=_sort_key)

    lines: list[str] = [
        "' _macros.puml — ArchiMate element macro library",
        "' Auto-generated from entity §display ###archimate blocks.",
        "' Do not edit manually — regenerated by generate_macros().",
        "'",
        "' USAGE CONVENTION (two-token pattern):",
        "'   Declare element inside a grouping rectangle:  DECL_DRV_Qw7Er1",
        "'   Reference element in a connection line:       DRV_Qw7Er1",
        "",
    ]

    current_domain = None
    for domain, macro_line, _ in entries:
        if domain != current_domain:
            if current_domain is not None:
                lines.append("")
            lines.append(f"' {'-' * 75}")
            lines.append(f"' {domain}")
            lines.append(f"' {'-' * 75}")
            current_domain = domain
        lines.append(macro_line)

    output = "\n".join(lines) + "\n"
    out_path = repo_root / "diagram-catalog" / "_macros.puml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output, encoding="utf-8")
    print(f"Written {len(entries)} macros → {out_path}")
    return out_path


def main() -> None:
    if len(sys.argv) > 1:
        repo_root = Path(sys.argv[1]).resolve()
    else:
        project_root = Path(__file__).resolve().parent.parent.parent
        repo_root = (
            project_root
            / "engagements"
            / "ENG-ARCH-REPO"
            / "architecture-repository"
        )

    if not repo_root.is_dir():
        print(f"ERROR: repo_root does not exist: {repo_root}", file=sys.stderr)
        sys.exit(1)

    generate_macros(repo_root)


if __name__ == "__main__":
    main()
